=== CometVisu/CometVisu/CometVisu/tags/post_0.6.0/visu/visu_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- basic types -->
<xsd:simpleType name="addr">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[0-9]{1,2}/[0-9]{1,2}/[0-9]{1,3}" />
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="dimension">
    <xsd:restriction base="xsd:string" />
</xsd:simpleType>

<xsd:simpleType name="uri">
    <xsd:restriction base="xsd:string" />
</xsd:simpleType>

<xsd:complexType name="address">
    <xsd:simpleContent>
        <xsd:extension base="addr">
            <xsd:attribute ref="transform" use="required" />
            <xsd:attribute ref="readonly" use="optional" />
            <xsd:attribute name="type" type="xsd:string" use="optional" />
            <xsd:attribute name="variant" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="entry">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="value" />
          <xsd:attributeGroup ref="range" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<!-- simple elements -->

<!-- attributes -->
<xsd:attribute name="min" type="xsd:decimal" />
<xsd:attribute name="max" type="xsd:decimal" />
<xsd:attribute name="step" type="xsd:decimal" />


<xsd:attribute name="transform" type="xsd:string" />
<xsd:attribute name="format" type="xsd:string" />

<xsd:attributeGroup name="range">
  <xsd:attribute name="range_min" type="xsd:float" />
  <xsd:attribute name="range_max" type="xsd:float" />
</xsd:attributeGroup>

<xsd:attribute name="mapping" type="xsd:string" />
<xsd:attribute name="styling" type="xsd:string" />
<xsd:attribute name="value" type="xsd:string" />

<xsd:attribute name="readonly" type="xsd:boolean" />
<xsd:attribute name="align" type="xsd:string" />

<!-- complex elements -->

<xsd:element name="pages">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="meta" />
            <xsd:element ref="page" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="design" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="meta">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="plugins" />
            <xsd:element ref="mappings" />
            <xsd:element ref="stylings" />
            <xsd:element ref="statusbar" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="plugins">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="plugin" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="plugin">
    <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="mappings">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="mapping" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="mapping">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="entry" type="entry" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="stylings">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="styling" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="styling">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="entry" type="entry" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:complexType name="status">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="type" type="xsd:string" use="optional" />
            <xsd:attribute name="condition" type="xsd:string" use="optional" />
            <xsd:attribute name="hrefextend" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:element name="statusbar">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="status" type="status" minOccurs="1" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<!-- define a page - if you add a new widget, you need to list it here -->
<xsd:element name="page">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <!-- visual effects -->
            <xsd:element name="line" type="line" />			
            <xsd:element name="break" type="break" />
            <xsd:element name="group" type="group" />
            <!-- list all possbile widgets here -->
            <xsd:element name="text" type="text" />
            <xsd:element name="switch" type="switch" />
            <xsd:element name="toggle" type="switch" />
            <xsd:element name="trigger" type="trigger" />
            <xsd:element name="multitrigger" type="multitrigger" />
            <xsd:element name="infotrigger" type="infotrigger" />
            <xsd:element name="designtoggle" type="designtoggle" />
            <xsd:element name="slide" type="slide" />
            <xsd:element name="info" type="info" />
            <xsd:element name="shade" type="info" />
            <xsd:element name="image" type="image" />
            <xsd:element name="video" type="video" />
            <xsd:element name="iframe" type="iframe" />
            <!-- available plugins - include not checked -->
            <xsd:element name="colorchooser" type="colorchooser" />
            <xsd:element name="diagram_popup" type="diagram_popup" />
            <xsd:element name="diagram_inline" type="diagram_inline" />
            <xsd:element ref="page" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="flavour" type="xsd:string" use="optional" />
        <xsd:attribute ref="align" use="optional" />
        <xsd:attribute name="ga" type="addr" use="optional" />
        <xsd:attribute name="visible" type="xsd:boolean" />
    </xsd:complexType>
</xsd:element>

<xsd:complexType name="group">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
		<!-- visual effects -->
        <xsd:element name="line" type="line" />			
		<xsd:element name="break" type="break" />
		<!-- list all possbile widgets here -->
        <xsd:element name="text" type="text" />
        <xsd:element name="switch" type="switch" />
        <xsd:element name="toggle" type="switch" />
        <xsd:element name="trigger" type="trigger" />
        <xsd:element name="multitrigger" type="multitrigger" />
		<xsd:element name="infotrigger" type="infotrigger" />
        <xsd:element name="designtoggle" type="designtoggle" />
        <xsd:element name="slide" type="slide" />
        <xsd:element name="info" type="info" />
        <xsd:element name="shade" type="info" />
        <xsd:element name="image" type="image" />
        <xsd:element name="video" type="video" />
        <xsd:element name="iframe" type="iframe" />
        <!-- available plugins - include not checked -->
        <xsd:element name="colorchooser" type="colorchooser" />
        <xsd:element name="diagram_popup" type="diagram_popup" />
        <xsd:element name="diagram_inline" type="diagram_inline" />
        <xsd:element ref="page" />
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="flavour" type="xsd:string" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>


<!-- more fun part - all widgets - if you add a new widget, you need to define it here -->

<xsd:complexType name="text">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute ref="align" use="optional"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="designtoggle">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string" />
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="switch">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
	<xsd:attribute name="on_value" type="xsd:string" use="optional" />
	<xsd:attribute name="off_value" type="xsd:string" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>

<xsd:complexType name="toogle">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>

<xsd:complexType name="trigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="value" use="required" />
    <xsd:attribute ref="mapping" use="optional"/>
    <xsd:attribute ref="styling" use="optional"/>
</xsd:complexType>

<xsd:complexType name="infotrigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="2" maxOccurs="unbounded"/>
    </xsd:choice>
    <xsd:attribute name="upvalue" type="xsd:string" use="optional"/>
	<xsd:attribute name="downvalue" type="xsd:string" use="optional"/>
	<xsd:attribute name="uplabel" type="xsd:string" use="optional"/>
	<xsd:attribute name="downlabel" type="xsd:string" use="optional"/>
    <xsd:attribute name="change" type="xsd:string" use="optional"/>
    <xsd:attribute ref="min" />
    <xsd:attribute ref="max" />
    <xsd:attribute ref="mapping" use="optional"/>
	<xsd:attribute ref="styling" use="optional"/>
    <xsd:attribute ref="align" use="optional" />
	<xsd:attribute ref="format" use="optional" />
	<xsd:attribute name="infoposition" type="xsd:decimal" use="optional" />
</xsd:complexType>

<xsd:complexType name="multitrigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute name="button1label" type="xsd:string" use="optional" />
    <xsd:attribute name="button1value" type="xsd:string" use="optional" />
    <xsd:attribute name="button2label" type="xsd:string" use="optional" />
    <xsd:attribute name="button2value" type="xsd:string" use="optional" />
    <xsd:attribute name="button3label" type="xsd:string" use="optional" />
    <xsd:attribute name="button3value" type="xsd:string" use="optional" />
    <xsd:attribute name="button4label" type="xsd:string" use="optional" />
    <xsd:attribute name="button4value" type="xsd:string" use="optional" />
</xsd:complexType>

<xsd:complexType name="slide">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" minOccurs="0" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="min" />
    <xsd:attribute ref="max" />
    <xsd:attribute ref="step" />
    <xsd:attribute ref="mapping" use="optional"/>
    <xsd:attribute ref="styling" use="optional" />
</xsd:complexType>

<xsd:complexType name="info">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1"/>
    </xsd:choice>
    <xsd:attribute ref="format" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
</xsd:complexType>

<xsd:complexType name="image">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
</xsd:complexType>

<xsd:complexType name="video">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
 </xsd:complexType>

<xsd:complexType name="iframe">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="frameborder" type="xsd:string" />
    <xsd:attribute name="background" type="xsd:string" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
</xsd:complexType>

<xsd:complexType name="colorchooser" >
    <xsd:choice maxOccurs="unbounded" minOccurs="0" >
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="3" maxOccurs="3"/>
    </xsd:choice>
</xsd:complexType>

<xsd:complexType name="diagram_inline">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="rrd" type="xsd:string" use="required" />
	        <xsd:attribute name="unit" type="xsd:string" use="optional" />
			<xsd:attribute name="width" type="dimension" use="optional"/>
			<xsd:attribute name="series" type="xsd:string" use="optional"/>
			<xsd:attribute name="height" type="dimension" use="optional"/>
			<xsd:attribute name="refresh" type="xsd:integer" use="optional" />
			<xsd:attribute name="period" type="xsd:string" use="optional" />
			<xsd:attribute name="datasource" type="xsd:string" use="optional" />
			<xsd:attribute name="linecolor" type="xsd:string" use="optional" />
			<xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
		</xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="diagram_popup" >
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="rrd" type="xsd:string" use="required" />
            <xsd:attribute name="unit" type="xsd:string" use="optional" />
            <xsd:attribute name="series" type="xsd:string" use="optional" />
            <xsd:attribute name="refresh" type="xsd:integer" use="optional" />
			<xsd:attribute name="period" type="xsd:string" use="optional" />
			<xsd:attribute name="datasource" type="xsd:string" use="optional" />
			<xsd:attribute name="tooltip" type="xsd:string" use="optional" />
			<xsd:attribute name="linecolor" type="xsd:string" use="optional" />
			<xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="diagram_info" >
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1"/>
    </xsd:choice>
    <xsd:attribute ref="format" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    <xsd:attribute name="rrd" type="xsd:string" use="required" />
    <xsd:attribute name="unit" type="xsd:string" use="optional" />
    <xsd:attribute name="series" type="xsd:string" use="optional" />
    <xsd:attribute name="refresh" type="xsd:integer" use="optional" />
    <xsd:attribute name="period" type="xsd:string" use="optional" />
    <xsd:attribute name="datasource" type="xsd:string" use="optional" />
    <xsd:attribute name="tooltip" type="xsd:string" use="optional" />
    <xsd:attribute name="linecolor" type="xsd:string" use="optional" />
    <xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
</xsd:complexType>

<xsd:complexType name="break" />

<xsd:complexType name="line" />

<!-- toggle is not yet implemented -->
<!-- shade is not yet implemented -->


</xsd:schema>

=== CometVisu/CometVisu/visu/visu_config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" design="pure" xsi:noNamespaceSchemaLocation="visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="colorchooser"/>
      <plugin name="diagram"/>
    </plugins>
    <mappings>
      <mapping name="Open_Close">
        <entry value="0">zu</entry>
        <entry value="1">offen</entry>
      </mapping>
      <mapping name="Close_Open">
        <entry value="0">offen</entry>
        <entry value="1">zu</entry>
      </mapping>
      <mapping name="On_Off">
        <entry value="0">Aus</entry>
        <entry value="1">An</entry>
      </mapping>
      <mapping name="Off_On">
        <entry value="0">An</entry>
        <entry value="1">Aus</entry>
      </mapping>
      <mapping name="KonnexHVAC">
        <entry value="auto">Auto</entry>
        <entry value="comfort">Komfort</entry>
        <entry value="standby">Stand By</entry>
        <entry value="economy">Economy</entry>
        <entry value="building_protection">Haus-Schutz</entry>
      </mapping>
    </mappings>
    <stylings>
      <styling name="Red_Green">
        <entry value="0">red</entry>
        <entry value="1">green</entry>
      </styling>
      <styling name="Green_Red">
        <entry value="0">green</entry>
        <entry value="1">red</entry>
      </styling>
      <styling name="Blue_Green_Red">
        <entry range_min="-100" range_max="20">blue</entry>
        <entry range_min="20"   range_max="22">green</entry>
        <entry range_min="22"   range_max="100">red</entry>
      </styling>
    </stylings>
    <statusbar>
      <status type="html"><![CDATA[
          <img src="icon/comet_64_ff8000.png" alt="CometVisu" /> by <a href="http://www.cometvisu.org/">CometVisu.org</a>
          - <a href=".?forceReload=true">Reload</a>
          - <a href="?config=demo">Widget Demo</a>
        ]]></status>
      <status type="html" condition="!edit" hrefextend="config"><![CDATA[
          - <a href="edit_config.html">Edit</a>
        ]]></status>
      <status type="html" condition="edit" hrefextend="all"><![CDATA[
          - <a href=".">normal Mode</a>
        ]]></status>
      <status type="html"><![CDATA[
          - <a href="check_config.php">Check Config</a>
          <div style="float:right;padding-right:0.5em">Version: 0.6.0-RC3</div>
        ]]></status>
    </statusbar>
  </meta>
  <page name="Start">
    <line/>
    <text align="center">Welcome to the CometVisu!</text>
    <line/>
  </page>
</pages>

=== CometVisu/CometVisu/source/resource/demo/visu_config_demo_controllerinput.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages lib_version="8" design="metal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="controllerinput"/>
    </plugins>
    <mappings/>
    <stylings/>
    <statusbar>
      <status type="html">&lt;img src="icon/comet_64_ff8000.png" alt="CometVisu" /&gt; by &lt;a href="http://www.cometvisu.org/"&gt;CometVisu.org&lt;/a&gt;
          - &lt;a href="manager.php"&gt;Config-Manager&lt;/a&gt;
          - &lt;a href=".?forceReload=true"&gt;Reload&lt;/a&gt;</status>
      <status type="html" condition="!edit" hrefextend="config">- &lt;a href="editor/"&gt;Edit&lt;/a&gt;</status>
      <status type="html" condition="edit" hrefextend="config">- &lt;a href="."&gt;normal Mode&lt;/a&gt;</status>
      <status type="html">- &lt;a href="?config=demo"&gt;Widget Demo&lt;/a&gt;</status>
      <status type="html" hrefextend="config">- &lt;a href="check_config.php"&gt;Check Config&lt;/a&gt;</status>
    </statusbar>
  </meta>
  <page name="Controller Input">
    <controllerinput min="-10" max="30" bind_click_to_widget="true" format="%.1fÂ°">
      <layout colspan="6" rowspan="5" />
      <label>Example Controller Input</label>
      <address transform="DPT:9.001" variant="actual" mode="read">12/7/90</address>
      <address transform="DPT:9.001" variant="setpoint" mode="readwrite">12/7/91</address>
      <address transform="DPT:9.001" variant="control" mode="read">12/7/92</address> 
      <rrd variant="actual" consolidationFunction="AVERAGE">28.F5432E020000_temp</rrd>
      <rrd variant="setpoint" consolidationFunction="AVERAGE">10_BadEG_FBH_Sollwert</rrd>
      <rrd variant="control" consolidationFunction="AVERAGE">10_BadEG_FBH_Regelung</rrd>
    </controllerinput>
    <text>
      <label>Change example values:</label>
      <layout colspan="6" rowspan="2" />
    </text>
    <slide min="-20" max="40" format="%.1f">
      <label>Actual value</label>
      <layout colspan="6" rowspan="1" />
      <address transform="DPT:9.001">12/7/90</address>
    </slide>
    <slide min="-20" max="40" format="%.1f">
      <label>Set point</label>
      <layout colspan="6" rowspan="1" />
      <address transform="DPT:9.001">12/7/91</address>
    </slide>
    <slide min="0" max="100" format="%.1f">
      <label>Controller Output</label>
      <layout colspan="6" rowspan="1" />
      <address transform="DPT:9.001">12/7/92</address>
    </slide>
  </page>
</pages>

=== CometVisu/CometVisu/src/config/visu_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" lib_version="8" design="pure" xsi:noNamespaceSchemaLocation="../visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="colorchooser"/>
      <plugin name="diagram"/>
      <plugin name="upnpcontroller"/>
    </plugins>
    <mappings>
      <mapping name="Close_Open">
        <entry value="0">zu</entry>
        <entry value="1">offen</entry>
      </mapping>
      <mapping name="Open_Close">
        <entry value="0">offen</entry>
        <entry value="1">zu</entry>
      </mapping>
      <mapping name="Off_On">
        <entry value="0">Aus</entry>
        <entry value="1">An</entry>
      </mapping>
      <mapping name="On_Off">
        <entry value="0">An</entry>
        <entry value="1">Aus</entry>
      </mapping>
      <mapping name="KonnexHVAC">
        <entry value="auto">Auto</entry>
        <entry value="comfort">Komfort</entry>
        <entry value="standby">Stand By</entry>
        <entry value="economy">Economy</entry>
        <entry value="building_protection">Haus-Schutz</entry>
      </mapping>
    </mappings>
    <stylings>
      <styling name="Red_Green">
        <entry value="0">red</entry>
        <entry value="1">green</entry>
      </styling>
      <styling name="Green_Red">
        <entry value="0">green</entry>
        <entry value="1">red</entry>
      </styling>
      <styling name="Blue_Green_Red">
        <entry range_min="-100" range_max="20">blue</entry>
        <entry range_min="20" range_max="22">green</entry>
        <entry range_min="22" range_max="100">red</entry>
      </styling>
    </stylings>
    <statusbar>
      <status type="html"><![CDATA[
          <img src="icon/comet_64_ff8000.png" alt="CometVisu" /> by <a href="http://www.cometvisu.org/">CometVisu.org</a>
          - <a href=".?forceReload=true">Reload</a>
        ]]></status>
      <status type="html" condition="!edit" hrefextend="config"><![CDATA[
          - <a href="editor/">Edit</a>
        ]]></status>
      <status type="html" condition="edit" hrefextend="config"><![CDATA[
          - <a href=".">normal Mode</a>
        ]]></status>
      <status type="html"><![CDATA[
          - <a href="?config=demo">Widget Demo</a>
        ]]></status>
      <status type="html" hrefextend="config"><![CDATA[
          - <a href="check_config.php">Check Config</a>
        ]]></status>
    </statusbar>
  </meta>
  <page name="Start">
    <line>
      <layout colspan="12"/>
    </line>
    <text align="center">
      <label>Welcome to the CometVisu!</label>
    </text>
    <line>
      <layout colspan="12"/>
    </line>
  </page>
</pages>
