=== CometVisu/CometVisu/CometVisu/tags/post_0.6.0/visu/visu_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<!-- basic types -->
<xsd:simpleType name="addr">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="[0-9]{1,2}/[0-9]{1,2}/[0-9]{1,3}" />
    </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="dimension">
    <xsd:restriction base="xsd:string" />
</xsd:simpleType>

<xsd:simpleType name="uri">
    <xsd:restriction base="xsd:string" />
</xsd:simpleType>

<xsd:complexType name="address">
    <xsd:simpleContent>
        <xsd:extension base="addr">
            <xsd:attribute ref="transform" use="required" />
            <xsd:attribute ref="readonly" use="optional" />
            <xsd:attribute name="type" type="xsd:string" use="optional" />
            <xsd:attribute name="variant" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="entry">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute ref="value" />
          <xsd:attributeGroup ref="range" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<!-- simple elements -->

<!-- attributes -->
<xsd:attribute name="min" type="xsd:decimal" />
<xsd:attribute name="max" type="xsd:decimal" />
<xsd:attribute name="step" type="xsd:decimal" />


<xsd:attribute name="transform" type="xsd:string" />
<xsd:attribute name="format" type="xsd:string" />

<xsd:attributeGroup name="range">
  <xsd:attribute name="range_min" type="xsd:float" />
  <xsd:attribute name="range_max" type="xsd:float" />
</xsd:attributeGroup>

<xsd:attribute name="mapping" type="xsd:string" />
<xsd:attribute name="styling" type="xsd:string" />
<xsd:attribute name="value" type="xsd:string" />

<xsd:attribute name="readonly" type="xsd:boolean" />
<xsd:attribute name="align" type="xsd:string" />

<!-- complex elements -->

<xsd:element name="pages">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="meta" />
            <xsd:element ref="page" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="design" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="meta">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="plugins" />
            <xsd:element ref="mappings" />
            <xsd:element ref="stylings" />
            <xsd:element ref="statusbar" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="plugins">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="plugin" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="plugin">
    <xsd:complexType>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="mappings">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="mapping" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="mapping">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="entry" type="entry" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:element name="stylings">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element ref="styling" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<xsd:element name="styling">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="entry" type="entry" minOccurs="1" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:element>

<xsd:complexType name="status">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="type" type="xsd:string" use="optional" />
            <xsd:attribute name="condition" type="xsd:string" use="optional" />
            <xsd:attribute name="hrefextend" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:element name="statusbar">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="status" type="status" minOccurs="1" />
        </xsd:choice>
    </xsd:complexType>
</xsd:element>

<!-- define a page - if you add a new widget, you need to list it here -->
<xsd:element name="page">
    <xsd:complexType>
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <!-- visual effects -->
            <xsd:element name="line" type="line" />			
            <xsd:element name="break" type="break" />
            <xsd:element name="group" type="group" />
            <!-- list all possbile widgets here -->
            <xsd:element name="text" type="text" />
            <xsd:element name="switch" type="switch" />
            <xsd:element name="toggle" type="switch" />
            <xsd:element name="trigger" type="trigger" />
            <xsd:element name="multitrigger" type="multitrigger" />
            <xsd:element name="infotrigger" type="infotrigger" />
            <xsd:element name="designtoggle" type="designtoggle" />
            <xsd:element name="slide" type="slide" />
            <xsd:element name="info" type="info" />
            <xsd:element name="shade" type="info" />
            <xsd:element name="image" type="image" />
            <xsd:element name="video" type="video" />
            <xsd:element name="iframe" type="iframe" />
            <!-- available plugins - include not checked -->
            <xsd:element name="colorchooser" type="colorchooser" />
            <xsd:element name="diagram_popup" type="diagram_popup" />
            <xsd:element name="diagram_inline" type="diagram_inline" />
            <xsd:element ref="page" />
        </xsd:choice>
        <xsd:attribute name="name" type="xsd:string" use="required" />
        <xsd:attribute name="flavour" type="xsd:string" use="optional" />
        <xsd:attribute ref="align" use="optional" />
        <xsd:attribute name="ga" type="addr" use="optional" />
        <xsd:attribute name="visible" type="xsd:boolean" />
    </xsd:complexType>
</xsd:element>

<xsd:complexType name="group">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
		<!-- visual effects -->
        <xsd:element name="line" type="line" />			
		<xsd:element name="break" type="break" />
		<!-- list all possbile widgets here -->
        <xsd:element name="text" type="text" />
        <xsd:element name="switch" type="switch" />
        <xsd:element name="toggle" type="switch" />
        <xsd:element name="trigger" type="trigger" />
        <xsd:element name="multitrigger" type="multitrigger" />
		<xsd:element name="infotrigger" type="infotrigger" />
        <xsd:element name="designtoggle" type="designtoggle" />
        <xsd:element name="slide" type="slide" />
        <xsd:element name="info" type="info" />
        <xsd:element name="shade" type="info" />
        <xsd:element name="image" type="image" />
        <xsd:element name="video" type="video" />
        <xsd:element name="iframe" type="iframe" />
        <!-- available plugins - include not checked -->
        <xsd:element name="colorchooser" type="colorchooser" />
        <xsd:element name="diagram_popup" type="diagram_popup" />
        <xsd:element name="diagram_inline" type="diagram_inline" />
        <xsd:element ref="page" />
    </xsd:choice>
    <xsd:attribute name="name" type="xsd:string" use="required" />
    <xsd:attribute name="flavour" type="xsd:string" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>


<!-- more fun part - all widgets - if you add a new widget, you need to define it here -->

<xsd:complexType name="text">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute ref="align" use="optional"/>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="designtoggle">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string" />
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="switch">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
	<xsd:attribute name="on_value" type="xsd:string" use="optional" />
	<xsd:attribute name="off_value" type="xsd:string" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>

<xsd:complexType name="toogle">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:attribute ref="align" use="optional" />
</xsd:complexType>

<xsd:complexType name="trigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="value" use="required" />
    <xsd:attribute ref="mapping" use="optional"/>
    <xsd:attribute ref="styling" use="optional"/>
</xsd:complexType>

<xsd:complexType name="infotrigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="2" maxOccurs="unbounded"/>
    </xsd:choice>
    <xsd:attribute name="upvalue" type="xsd:string" use="optional"/>
	<xsd:attribute name="downvalue" type="xsd:string" use="optional"/>
	<xsd:attribute name="uplabel" type="xsd:string" use="optional"/>
	<xsd:attribute name="downlabel" type="xsd:string" use="optional"/>
    <xsd:attribute name="change" type="xsd:string" use="optional"/>
    <xsd:attribute ref="min" />
    <xsd:attribute ref="max" />
    <xsd:attribute ref="mapping" use="optional"/>
	<xsd:attribute ref="styling" use="optional"/>
    <xsd:attribute ref="align" use="optional" />
	<xsd:attribute ref="format" use="optional" />
	<xsd:attribute name="infoposition" type="xsd:decimal" use="optional" />
</xsd:complexType>

<xsd:complexType name="multitrigger">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute name="button1label" type="xsd:string" use="optional" />
    <xsd:attribute name="button1value" type="xsd:string" use="optional" />
    <xsd:attribute name="button2label" type="xsd:string" use="optional" />
    <xsd:attribute name="button2value" type="xsd:string" use="optional" />
    <xsd:attribute name="button3label" type="xsd:string" use="optional" />
    <xsd:attribute name="button3value" type="xsd:string" use="optional" />
    <xsd:attribute name="button4label" type="xsd:string" use="optional" />
    <xsd:attribute name="button4value" type="xsd:string" use="optional" />
</xsd:complexType>

<xsd:complexType name="slide">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" minOccurs="0" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1" />
    </xsd:choice>
    <xsd:attribute ref="min" />
    <xsd:attribute ref="max" />
    <xsd:attribute ref="step" />
    <xsd:attribute ref="mapping" use="optional"/>
    <xsd:attribute ref="styling" use="optional" />
</xsd:complexType>

<xsd:complexType name="info">
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1"/>
    </xsd:choice>
    <xsd:attribute ref="format" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
</xsd:complexType>

<xsd:complexType name="image">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
</xsd:complexType>

<xsd:complexType name="video">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
 </xsd:complexType>

<xsd:complexType name="iframe">
    <xsd:choice maxOccurs="unbounded" minOccurs="0">
      <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    </xsd:choice>
    <xsd:attribute name="src" type="uri" use="required" />
    <xsd:attribute name="width" type="dimension" />
    <xsd:attribute name="height" type="dimension" />
    <xsd:attribute name="frameborder" type="xsd:string" />
    <xsd:attribute name="background" type="xsd:string" />
    <xsd:attribute name="refresh" type="xsd:decimal" />
</xsd:complexType>

<xsd:complexType name="colorchooser" >
    <xsd:choice maxOccurs="unbounded" minOccurs="0" >
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="3" maxOccurs="3"/>
    </xsd:choice>
</xsd:complexType>

<xsd:complexType name="diagram_inline">
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="rrd" type="xsd:string" use="required" />
	        <xsd:attribute name="unit" type="xsd:string" use="optional" />
			<xsd:attribute name="width" type="dimension" use="optional"/>
			<xsd:attribute name="series" type="xsd:string" use="optional"/>
			<xsd:attribute name="height" type="dimension" use="optional"/>
			<xsd:attribute name="refresh" type="xsd:integer" use="optional" />
			<xsd:attribute name="period" type="xsd:string" use="optional" />
			<xsd:attribute name="datasource" type="xsd:string" use="optional" />
			<xsd:attribute name="linecolor" type="xsd:string" use="optional" />
			<xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
		</xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="diagram_popup" >
    <xsd:simpleContent>
        <xsd:extension base="xsd:string">
            <xsd:attribute name="rrd" type="xsd:string" use="required" />
            <xsd:attribute name="unit" type="xsd:string" use="optional" />
            <xsd:attribute name="series" type="xsd:string" use="optional" />
            <xsd:attribute name="refresh" type="xsd:integer" use="optional" />
			<xsd:attribute name="period" type="xsd:string" use="optional" />
			<xsd:attribute name="datasource" type="xsd:string" use="optional" />
			<xsd:attribute name="tooltip" type="xsd:string" use="optional" />
			<xsd:attribute name="linecolor" type="xsd:string" use="optional" />
			<xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="diagram_info" >
    <xsd:choice maxOccurs="unbounded" minOccurs="1">
        <xsd:element name="label" type="xsd:string" maxOccurs="1" />
        <xsd:element name="address" type="address" minOccurs="1"/>
    </xsd:choice>
    <xsd:attribute ref="format" use="optional" />
    <xsd:attribute ref="styling" use="optional" />
    <xsd:attribute ref="mapping" use="optional" />
    <xsd:element name="label" type="xsd:string" maxOccurs="1" />
    <xsd:attribute name="rrd" type="xsd:string" use="required" />
    <xsd:attribute name="unit" type="xsd:string" use="optional" />
    <xsd:attribute name="series" type="xsd:string" use="optional" />
    <xsd:attribute name="refresh" type="xsd:integer" use="optional" />
    <xsd:attribute name="period" type="xsd:string" use="optional" />
    <xsd:attribute name="datasource" type="xsd:string" use="optional" />
    <xsd:attribute name="tooltip" type="xsd:string" use="optional" />
    <xsd:attribute name="linecolor" type="xsd:string" use="optional" />
    <xsd:attribute name="gridcolor" type="xsd:string" use="optional" />
</xsd:complexType>

<xsd:complexType name="break" />

<xsd:complexType name="line" />

<!-- toggle is not yet implemented -->
<!-- shade is not yet implemented -->


</xsd:schema>

=== CometVisu/CometVisu/CometVisu/trunk/src/config/demo/visu_config_emptyx.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" lib_version="5" design="pure" xsi:noNamespaceSchemaLocation="../visu_config.xsd">
  <meta>
    <plugins>
    </plugins>
    <mappings>
    </mappings>
    <stylings>
    </stylings>
    <statusbar>
    </statusbar>
  </meta>
  <page name="Start">
    <text align="center">
      <label>Welcome to the CometVisu!</label>
    </text>
  </page>
</pages>

=== CometVisu/CometVisu/CometVisu/trunk/visu/visu_config_2d3d.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" design="pure" xsi:noNamespaceSchemaLocation="visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="colorchooser"/>
      <plugin name="diagram"/>
    </plugins>
    <mappings>
      <mapping name="Open_Close">
        <entry value="0">zu</entry>
        <entry value="1">offen</entry>
      </mapping>
      <mapping name="Close_Open">
        <entry value="0">offen</entry>
        <entry value="1">zu</entry>
      </mapping>
      <mapping name="On_Off">
        <entry value="0">Aus</entry>
        <entry value="1">An</entry>
      </mapping>
      <mapping name="Off_On">
        <entry value="0">An</entry>
        <entry value="1">Aus</entry>
      </mapping>
      <mapping name="KonnexHVAC">
        <entry value="auto">Auto</entry>
        <entry value="comfort">Komfort</entry>
        <entry value="standby">Stand By</entry>
        <entry value="economy">Economy</entry>
        <entry value="building_protection">Haus-Schutz</entry>
      </mapping>
    </mappings>
    <stylings>
      <styling name="Red_Green">
        <entry value="0">red</entry>
        <entry value="1">green</entry>
      </styling>
      <styling name="Green_Red">
        <entry value="0">green</entry>
        <entry value="1">red</entry>
      </styling>
      <styling name="Blue_Green_Red">
        <entry range_min="-100" range_max="20">blue</entry>
        <entry range_min="20" range_max="22">green</entry>
        <entry range_min="22" range_max="100">red</entry>
      </styling>
    </stylings>
    <statusbar>
      <status type="html"><![CDATA[
          <img src="icon/comet_64_ff8000.png" alt="CometVisu" /> by <a href="http://www.cometvisu.org/">CometVisu.org</a>
          - <a href=".?forceReload=true">Reload</a>
          - <a href="?config=demo">Widget Demo</a>
        ]]></status>
      <status type="html" condition="!edit" hrefextend="config"><![CDATA[
          - <a href="edit_config.html">Edit</a>
        ]]></status>
      <status type="html" condition="edit" hrefextend="all"><![CDATA[
          - <a href=".">normal Mode</a>
        ]]></status>
      <status type="html"><![CDATA[
          - <a href="check_config.php">Check Config</a>
          <div style="float:right;padding-right:0.5em">Version: SVN</div>
        ]]></status>
    </statusbar>
  </meta>
  <page name="Start" type="text">
    <line/>
    <text align="center">Welcome to the CometVisu!</text>
    <break/>
    <page name="2D Demo" type="2d" backdrop="media/demo_2d_backdrop_red_pot.svg">
      <slide>
        <layout x="0px" y="470px" width="600px" />
        <label>Level</label>
        <address transform="DPT:5.001" type="">12/7/52</address>
      </slide>
      <info format="%.2f">
        <layout x="350px" y="370px" />
        <address transform="DPT:5.001" type="">12/7/52</address>
      </info>
    </page>
    <page name="3D Demo" type="3d" backdrop="floorplan_demo.xml" azimut="12/7/53" elevation="12/7/54" floor="12/7/51">
      <info format="%.2f">
        <layout x="3.5" y="3.7" z="1.0"/>
        <address transform="DPT:5.001" type="">12/7/53</address>
      </info>
      <slide min="0" max="6.283185307179586">
        <layout x="0px" y="570px" width="600px" />
        <label>Azimut</label>
        <address transform="DPT:5.001" type="">12/7/53</address>
      </slide>
      <slide min="0" max="1.5707963267948966">
        <layout x="400px" y="570px" width="600px" />
        <label>Elevation</label>
        <address transform="DPT:5.001" type="">12/7/54</address>
      </slide>
      <trigger value="0">
        <layout x="0px" y="150px" width="600px" />
        <label>Underground</label>
        <address transform="DPT:5.004" readonly="false" type="">12/7/51</address>
      </trigger>
      <trigger value="1">
        <layout x="0px" y="100px" width="600px" />
        <label>Ground</label>
        <address transform="DPT:5.004" readonly="false" type="">12/7/51</address>
      </trigger>
    </page>
    <line/>
  </page>
</pages>

=== CometVisu/CometVisu/CometVisu/branches/release_0.8.0-RC1/src/config/visu_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<pages lib_version="3" design="pure" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="colorchooser"/>
      <plugin name="diagram"/>
      <plugin name="upnpcontroller"/>
    </plugins>
    <mappings>
      <mapping name="Close_Open">
        <entry value="0">zu</entry>
        <entry value="1">offen</entry>
      </mapping>
      <mapping name="Open_Close">
        <entry value="0">offen</entry>
        <entry value="1">zu</entry>
      </mapping>
      <mapping name="Off_On">
        <entry value="0">Aus</entry>
        <entry value="1">An</entry>
      </mapping>
      <mapping name="On_Off">
        <entry value="0">An</entry>
        <entry value="1">Aus</entry>
      </mapping>
      <mapping name="KonnexHVAC">
        <entry value="auto">Auto</entry>
        <entry value="comfort">Komfort</entry>
        <entry value="standby">Stand By</entry>
        <entry value="economy">Economy</entry>
        <entry value="building_protection">Haus-Schutz</entry>
      </mapping>
    </mappings>
    <stylings>
      <styling name="Red_Green">
        <entry value="0">red</entry>
        <entry value="1">green</entry>
      </styling>
      <styling name="Green_Red">
        <entry value="0">green</entry>
        <entry value="1">red</entry>
      </styling>
      <styling name="Blue_Green_Red">
        <entry range_min="-100" range_max="20">blue</entry>
        <entry range_min="20" range_max="22">green</entry>
        <entry range_min="22" range_max="100">red</entry>
      </styling>
    </stylings>
    <statusbar>
      <status type="html">&lt;img src="icon/comet_64_ff8000.png" alt="CometVisu" /&gt; by &lt;a href="http://www.cometvisu.org/"&gt;CometVisu.org&lt;/a&gt;
        - &lt;a href=".?forceReload=true"&gt;Reload&lt;/a&gt;</status>
      <status type="html" condition="!edit" hrefextend="config"> - &lt;a href="editor/"&gt;Edit&lt;/a&gt;</status>
      <status type="html" condition="edit" hrefextend="config"> - &lt;a href="."&gt;normal Mode&lt;/a&gt;</status>
      <status type="html"> - &lt;a href="?config=demo"&gt;Widget Demo&lt;/a&gt;</status>
      <status type="html" hrefextend="config"> - &lt;a href="check_config.php"&gt;Check Config&lt;/a&gt;</status>
    </statusbar>
  </meta>
  <page name="Start">
    <line/>
    <text align="center">
      <label>Welcome to the CometVisu!</label>
    </text>
    <line/>
  </page>
</pages>

=== CometVisu/CometVisu/CometVisu/trunk/visu/visu_config_neu.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<pages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" design="pure" xsi:noNamespaceSchemaLocation="visu_config.xsd">
  <meta>
    <plugins>
      <plugin name="colorchooser"/>
    <!--
      <plugin name="diagram"/>
    -->
    </plugins>
    <mappings>
      <mapping name="OpenClose">
        <entry value="0">zu</entry>
        <entry value="1">offen</entry>
      </mapping>
      <mapping name="OnOff">
        <entry value="0">Aus</entry>
        <entry value="1">An</entry>
      </mapping>
      <mapping name="Sign">
        <entry range_min="-1e99" range_max="0">Negativ</entry>
        <entry value="0">Null</entry>
        <entry range_min="0" range_max="1e99">Positiv</entry>
      </mapping>
    </mappings>
    <stylings>
      <styling name="RedGreen">
        <entry value="0">red</entry>
        <entry value="1">green</entry>
      </styling>
      <styling name="GreenRed">
        <entry value="0">green</entry>
        <entry value="1">red</entry>
      </styling>
      <styling name="BluePurpleRed">
        <entry range_min="-100" range_max="0">blue</entry>
        <entry value="0">purple</entry>
        <entry range_min="0" range_max="100">red</entry>
      </styling>
    </stylings>
    <statusbar>
      <status type="html"><![CDATA[
          <img src="icon/comet_64_ff8000.png" alt="CometVisu" /> by <a href="http://www.cometvisu.org/">CometVisu.org</a>
          - <a href=".?config=neu">Reload</a>
          - <a href=".">Default Config</a>
        ]]></status>
      <status type="html" condition="!edit"><![CDATA[
          - <a href="edit_config.html">Edit</a>
        ]]></status>
      <status type="html" condition="edit"><![CDATA[
          - <a href=".">normal Mode</a>
        ]]></status>
      <status type="html"><![CDATA[
          - <a href="check_config.php">Check Config</a>
        ]]></status>
    </statusbar>
  </meta>
  <page name="Ãœbersicht">
    <text align="center">CometVisu format neu</text>
    <info styling="BluePurpleRed">
      <label>Slide Info</label>
      <address src="12/4/250" transform="DPT:9" />
      <address src="12/4/251" transform="DPT:9.001" />
    </info>
    <switch mapping="OnOff" styling="RedGreen">
      <label>Terrase Licht</label>
      <address src="1/0/2" transform="DPT:1.001" />
      <address src="12/4/253" transform="DPT:9.001" readonly="true" />
    </switch>
    <slide min="-18" max="26">
      <label>Slide</label>
      <address src="12/4/250" transform="DPT:9" />
    </slide>
    <break />
    <trigger value="0" mapping="OnOff">
      <label>Terrase Licht 0</label>
      <address src="1/0/2" transform="DPT:1.001" />
    </trigger>
    <trigger value="1" mapping="OnOff">
      <label>Terrase Licht 1</label>
      <address src="1/0/2" transform="DPT:1.001" />
    </trigger>
    <line />
    <image src="icon/comet_128_ff8000.png" width="500px" height="46px"/>
    <image src="http://www.e-zeeinternet.com/count.php?page=546016&amp;style=default&amp;nbdigits=9&amp;reloads=1" refresh="10">
      <label>Update every 10 sec</label>
    </image>
    <designtoggle>Change design</designtoggle>
    <page name="iframe Test">
      <iframe src="http://www.cometvisu.org" width="500px" height="500px"/>
    </page>
    <colorchooser>
      <label>A colorChooser</label>
      <address src="1/2/59" transform="DPT:5.001" color="r" />
      <address src="1/2/60" transform="DPT:5.001" color="g" />
      <address src="1/2/61" transform="DPT:5.001" color="b" />
    </colorchooser>
    <info><label>R</label><address src="1/2/59" transform="DPT:5.001" /></info>
    <info><label>G</label><address src="1/2/60" transform="DPT:5.001" /></info>
    <info><label>B</label><address src="1/2/61" transform="DPT:5.001" /></info>
    <slide><label>B</label><address src="1/2/61" transform="DPT:5.001" /></slide>
  </page>
</pages>
